name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Going to work
        run: echo "Hello World!"

  test-update-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
